### PR TITLE
download: Add logos to platform headings

### PR DESCRIPTION
**Pull request by jamesobutler**
Addresses some items mentioned in https://github.com/Slicer/slicer_download/issues/9#issue-950375128, this PR 
- adds logos to the platform headings on the download page like https://code.visualstudio.com/Download
- removes the "Installers" heading

Like the Visual Studio Code download page, I have downloaded the logos to upload as a website asset source rather than embedding a logo from the Wikimedia source. Logos acquired from the following
- https://commons.wikimedia.org/wiki/File:Windows_logo_-_2021.svg
- https://commons.wikimedia.org/wiki/File:Apple_logo_black.svg
- https://commons.wikimedia.org/wiki/File:Tux.svg

### CODE REVIEW

**Comment by jamesobutler** [comment]
@jcfr Is there any download.slicer.org deploy preview?

**Comment by jcfr** [comment]
Something is not working as expected ... I will follow up.

**Comment by jcfr** [comment]
> Is there any download.slicer.org deploy preview?

Following https://github.com/Slicer/slicer.org/commit/e3fd2263a8d9c6b9a2cca9c0f283c4f7bbcccf86, the list of status now include the following:

image

Click on the `Details` link will redirect to https://deploy-download-preview--slicer-org.netlify.app/download.html

Note that due to limitation with the Netlify integration ... the preview for the "mock" download site will always be associated with the same branch. This means that if another pull request is updated .. the preview will be overridden.

**Comment by jcfr** [comment]
Closing. 

Due to limitation of the continuous integration infrastructure preventing us from generating download preview for pull request originating from forks, this pull request is now superseded  by https://github.com/Slicer/slicer.org/pull/136

**Pull request closed without merging**
