### PR TITLE
RFC: change top Feedback link to Forum.

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

**Comment by ihnorton** [comment]
Quasi-preview: http://htmlpreview.github.io/?https://github.com/Slicer/slicer.org/blob/ihnorton-patch-1/index.html

**Comment by jcfr** [comment]
Could you squash the two commits? :+1:

**Comment by ihnorton** [comment]
Is there a reason Squash and Merge is disabled?

image

**Comment by jcfr** [comment]
It is now enabled.

**Comment by ihnorton** [comment]
@freephile this does not seem to have propagated to the live site.

**Comment by jcfr** [comment]
@freephile I was out of town the past few weeks and probably missed some email. I guess the `slicer-org` branch is the one being synchronized instead of `gh-pages`

**Comment by jcfr** [comment]
Here is the related thread: https://discourse.slicer.org/t/its-all-about-transitions-lets-talk-about-slicers-landing-page/113/22

**Comment by jcfr** [comment]
I just pushed the change on `slicer-org` branch

**Comment by jcfr** [comment]
To avoid confusion, I removed `gh-pages` branch

**Pull request merged**
