### PR TITLE
carousel: Update "1 million downloads milestone" image

### PR DESCRIPTION
**Pull request by jcfr**
Follow up of 81bd31a (carousel: Add 1 million downloads milestone) to account for change introduced in Slicer/slicer_download_stats@73ec581eb (index: Rename "Slicer4" to "Slicer") through https://github.com/Slicer/slicer_download_stats/pull/2

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
You might as well make sure to use the Slicer 5 logo on the download stats page if you're going to update this screenshot.

**Comment by jcfr** [comment]
> use the Slicer 5 logo on the download stats page

Good point. I gonna update the download stat site and then follow up with an update here.

**Comment by jamesobutler** [comment]
@jcfr Here's a new image with updated logo. Details the specific day when the page recorded crossing 1 million downloads. It is not exactly the same as the previous in that it includes 5.0 and 5.1 versions.
image

**Comment by jcfr** [comment]
For some reason, the GitHub preview shows the same content before/after.
https://github.com/Slicer/slicer.org/pull/150/files#diff-1f4dbcde0c156397332daf09f0cb90f0190d5172ca32cc7a7177c9777092b24a

**Comment by jamesobutler** [comment]
> https://github.com/Slicer/slicer.org/pull/150/files#diff-1f4dbcde0c156397332daf09f0cb90f0190d5172ca32cc7a7177c9777092b24a

It's a game of spot the difference, but I see the change from "Slicer4" to "Slicer". Note that I haven't pushed the new image to this branch. Only posted it as a comment for you to modify your commit.

**Comment by jcfr** [comment]
> Note that I haven't pushed the new image to this branch. Only posted it as a comment for you to modify your commit.

Gotcha. I will get to this later this evening .. now getting in the :car:

**Comment by jamesobutler** [comment]
@jcfr I've pushed a commit to update the image to include the latest changes regarding title and logo used on the download stats page.

**Comment by jamesobutler** [comment]
Looks like aspect ratio matters. The import parts of the image got cut off with my latest image.

image

**Pull request merged**
